// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dedialilbuseilgqgmeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZGlhbGlsYnVzZWlsZ3FnbWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTczMzYsImV4cCI6MjA2MjA3MzMzNn0.gLnxv3YT0psp6hO-AzSp0v7TVVUcbIwp149tE_hEnzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);